/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AboutRouteImport } from './routes/about'
import { Route as UsernameDialogRouteImport } from './routes/UsernameDialog'
import { Route as LandingPageRouteImport } from './routes/LandingPage'
import { Route as HeaderRouteImport } from './routes/Header'
import { Route as AuthRouteImport } from './routes/Auth'
import { Route as AccountRouteImport } from './routes/Account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PokeListPokeListRouteImport } from './routes/pokeList/PokeList'
import { Route as PokeListPokeCardRouteImport } from './routes/pokeList/PokeCard'

const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameDialogRoute = UsernameDialogRouteImport.update({
  id: '/UsernameDialog',
  path: '/UsernameDialog',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPageRoute = LandingPageRouteImport.update({
  id: '/LandingPage',
  path: '/LandingPage',
  getParentRoute: () => rootRouteImport,
} as any)
const HeaderRoute = HeaderRouteImport.update({
  id: '/Header',
  path: '/Header',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/Auth',
  path: '/Auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/Account',
  path: '/Account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokeListPokeListRoute = PokeListPokeListRouteImport.update({
  id: '/pokeList/PokeList',
  path: '/pokeList/PokeList',
  getParentRoute: () => rootRouteImport,
} as any)
const PokeListPokeCardRoute = PokeListPokeCardRouteImport.update({
  id: '/pokeList/PokeCard',
  path: '/pokeList/PokeCard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Auth': typeof AuthRoute
  '/Header': typeof HeaderRoute
  '/LandingPage': typeof LandingPageRoute
  '/UsernameDialog': typeof UsernameDialogRoute
  '/about': typeof AboutRoute
  '/pokeList/PokeCard': typeof PokeListPokeCardRoute
  '/pokeList/PokeList': typeof PokeListPokeListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Auth': typeof AuthRoute
  '/Header': typeof HeaderRoute
  '/LandingPage': typeof LandingPageRoute
  '/UsernameDialog': typeof UsernameDialogRoute
  '/about': typeof AboutRoute
  '/pokeList/PokeCard': typeof PokeListPokeCardRoute
  '/pokeList/PokeList': typeof PokeListPokeListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Account': typeof AccountRoute
  '/Auth': typeof AuthRoute
  '/Header': typeof HeaderRoute
  '/LandingPage': typeof LandingPageRoute
  '/UsernameDialog': typeof UsernameDialogRoute
  '/about': typeof AboutRoute
  '/pokeList/PokeCard': typeof PokeListPokeCardRoute
  '/pokeList/PokeList': typeof PokeListPokeListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Account'
    | '/Auth'
    | '/Header'
    | '/LandingPage'
    | '/UsernameDialog'
    | '/about'
    | '/pokeList/PokeCard'
    | '/pokeList/PokeList'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Account'
    | '/Auth'
    | '/Header'
    | '/LandingPage'
    | '/UsernameDialog'
    | '/about'
    | '/pokeList/PokeCard'
    | '/pokeList/PokeList'
  id:
    | '__root__'
    | '/'
    | '/Account'
    | '/Auth'
    | '/Header'
    | '/LandingPage'
    | '/UsernameDialog'
    | '/about'
    | '/pokeList/PokeCard'
    | '/pokeList/PokeList'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AuthRoute: typeof AuthRoute
  HeaderRoute: typeof HeaderRoute
  LandingPageRoute: typeof LandingPageRoute
  UsernameDialogRoute: typeof UsernameDialogRoute
  AboutRoute: typeof AboutRoute
  PokeListPokeCardRoute: typeof PokeListPokeCardRoute
  PokeListPokeListRoute: typeof PokeListPokeListRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/UsernameDialog': {
      id: '/UsernameDialog'
      path: '/UsernameDialog'
      fullPath: '/UsernameDialog'
      preLoaderRoute: typeof UsernameDialogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/LandingPage': {
      id: '/LandingPage'
      path: '/LandingPage'
      fullPath: '/LandingPage'
      preLoaderRoute: typeof LandingPageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Header': {
      id: '/Header'
      path: '/Header'
      fullPath: '/Header'
      preLoaderRoute: typeof HeaderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Auth': {
      id: '/Auth'
      path: '/Auth'
      fullPath: '/Auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Account': {
      id: '/Account'
      path: '/Account'
      fullPath: '/Account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokeList/PokeList': {
      id: '/pokeList/PokeList'
      path: '/pokeList/PokeList'
      fullPath: '/pokeList/PokeList'
      preLoaderRoute: typeof PokeListPokeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokeList/PokeCard': {
      id: '/pokeList/PokeCard'
      path: '/pokeList/PokeCard'
      fullPath: '/pokeList/PokeCard'
      preLoaderRoute: typeof PokeListPokeCardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AuthRoute: AuthRoute,
  HeaderRoute: HeaderRoute,
  LandingPageRoute: LandingPageRoute,
  UsernameDialogRoute: UsernameDialogRoute,
  AboutRoute: AboutRoute,
  PokeListPokeCardRoute: PokeListPokeCardRoute,
  PokeListPokeListRoute: PokeListPokeListRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
