-- =============================================================================
-- Trade notifications
-- =============================================================================
-- One row per thing a player should hear about on one of their Pocket
-- accounts: an offer received, their offer accepted or declined, a trade
-- cancelled, the other player marking a trade done. Rows are written by a
-- trigger on trade_offer; players can only read theirs and mark them read.
-- =============================================================================

create table public.notification (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  tcg_account_id uuid not null references public.player_tcg_account (tcg_account_id) on delete cascade,
  kind text not null check (kind in ('offer_received', 'offer_accepted', 'offer_declined', 'offer_cancelled', 'partner_done')),
  trade_offer_id bigint references public.trade_offer (id) on delete cascade,
  -- what the message shows, from this player's point of view
  partner_name text not null,
  my_card_id uuid references public.card (card_id),
  their_card_id uuid references public.card (card_id),
  exclusive boolean not null default false,
  read_at timestamptz,
  created_at timestamptz not null default now()
);
comment on table public.notification is 'Trade notifications for a player''s Pocket accounts (written by the trade_offer trigger)';
create index notification_user_created on public.notification (user_id, created_at desc);
create index notification_trade_offer on public.notification (trade_offer_id);

alter table public.notification enable row level security;
create policy "Players can read their notifications"
  on public.notification for select to authenticated using (user_id = (select auth.uid()));
create policy "Players can mark their notifications read"
  on public.notification for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
revoke all on public.notification from anon, authenticated;
grant select on public.notification to authenticated;
grant update (read_at) on public.notification to authenticated;


-- Adds a notification for one side of an offer (p_account is the side told)
create or replace function public.notify_trade(p_offer public.trade_offer, p_account uuid, p_kind text) returns void
  language sql security definer set search_path = ''
  as $$
    insert into public.notification (user_id, tcg_account_id, kind, trade_offer_id, partner_name, my_card_id, their_card_id, exclusive)
    select a.user_id, p_account, p_kind, p_offer.id,
      public.trade_account_name(case when p_account = p_offer.from_account then p_offer.to_account else p_offer.from_account end),
      case when p_account = p_offer.from_account then p_offer.give_card_id else p_offer.get_card_id end,
      case when p_account = p_offer.from_account then p_offer.get_card_id else p_offer.give_card_id end,
      p_offer.exclusive_trade_id is not null
    from public.player_tcg_account a where a.tcg_account_id = p_account
  $$;
revoke all on function public.notify_trade(public.trade_offer, uuid, text) from public, anon, authenticated;


create or replace function public.trade_offer_notify() returns trigger
  language plpgsql security definer set search_path = ''
  as $$
begin
  if tg_op = 'INSERT' then
    perform public.notify_trade(new, new.to_account, 'offer_received');
    return new;
  end if;

  if new.status <> old.status then
    -- Once an offer is answered or withdrawn, its "offer received" note is done with
    if old.status = 'pending' then
      if new.status = 'cancelled' then
        delete from public.notification
          where trade_offer_id = new.id and kind = 'offer_received' and read_at is null;
      else
        update public.notification set read_at = now()
          where trade_offer_id = new.id and kind = 'offer_received' and read_at is null;
      end if;
    end if;

    if old.status = 'pending' and new.status = 'accepted' then
      perform public.notify_trade(new, new.from_account, 'offer_accepted');
    elsif old.status = 'pending' and new.status = 'declined' then
      perform public.notify_trade(new, new.from_account, 'offer_declined');
    elsif old.status = 'accepted' and new.status = 'cancelled' then
      -- tell the side that didn't cancel
      perform public.notify_trade(new, case when public.owns_tcg_account(new.from_account) then new.to_account else new.from_account end, 'offer_cancelled');
    end if;
  end if;

  if new.from_done and not old.from_done then
    perform public.notify_trade(new, new.to_account, 'partner_done');
  end if;
  if new.to_done and not old.to_done then
    perform public.notify_trade(new, new.from_account, 'partner_done');
  end if;
  return new;
end $$;
revoke all on function public.trade_offer_notify() from public, anon, authenticated;

create trigger trade_offer_notify after insert or update on public.trade_offer
  for each row execute function public.trade_offer_notify();


-- Live updates for the bell (rows are still filtered by the select policy)
do $$
begin
  if exists (select 1 from pg_publication where pubname = 'supabase_realtime') then
    alter publication supabase_realtime add table public.notification;
  end if;
end $$;
