-- =============================================================================
-- Trading between players
-- =============================================================================
-- The app finds players who have cards you want (in the language you want) and
-- lets you offer one of your cards of the same rarity for one of theirs. They
-- accept or decline; once accepted both players see each other's Pocket friend
-- ID and do the trade in the game. Each player then marks it done, which takes
-- the cards off their own lists.
--
-- Writes to trade_offer only happen through the functions below (security
-- definer), which check ownership and the game's trading rules.
-- =============================================================================


-- Pocket friend IDs are 16 digits, which doesn't fit the integer column the
-- account form saves into (max 2147483647). Store them as text, digits only.
alter table public.player_tcg_account alter column tcg_id type text using tcg_id::text;
alter table public.player_tcg_account add constraint player_tcg_account_tcg_id_digits check (tcg_id ~ '^[0-9]{1,32}$');


-- Rarities the game lets players trade. Left empty (null), a rarity follows
-- the game's default below, which also covers rarities added later by the card
-- sync. Override one with e.g.
--   update public.rarity set tradable = true where name = 'Two Star';
alter table public.rarity add column if not exists tradable boolean;

create or replace function public.rarity_is_tradable(p_rarity_id uuid) returns boolean
  language sql stable set search_path = ''
  as $$
    select coalesce(r.tradable, r.name in ('One Diamond', 'Two Diamond', 'Three Diamond', 'Four Diamond', 'One Star'))
    from public.rarity r where r.rarity_id = p_rarity_id
  $$;


-- -----------------------------------------------------------------------------
-- Wishlists and trade lists are public (signed-out visitors included), so
-- players can find each other. They only hold the account id, card, language
-- and quantity; names and friend IDs are not exposed by these tables.
-- -----------------------------------------------------------------------------
drop policy "Users can read their own wishlist" on public.wishlist;
drop policy "Users can read their own trade cards" on public.cards_available_for_trade;

create policy "Anyone can read wishlists"
  on public.wishlist for select to anon, authenticated using (true);
create policy "Anyone can read trade lists"
  on public.cards_available_for_trade for select to anon, authenticated using (true);

grant select on public.wishlist, public.cards_available_for_trade to anon;


-- -----------------------------------------------------------------------------
-- trade_offer: one card for one card between two Pocket accounts
--   from_account offers give_card (from its trade list) for get_card (from
--   to_account's trade list).
-- -----------------------------------------------------------------------------
create table public.trade_offer (
  id bigint generated by default as identity primary key,
  from_account uuid not null references public.player_tcg_account (tcg_account_id) on delete cascade,
  to_account uuid not null references public.player_tcg_account (tcg_account_id) on delete cascade,
  give_card_id uuid not null references public.card (card_id),
  give_language text not null check (public.is_card_language(give_language)),
  get_card_id uuid not null references public.card (card_id),
  get_language text not null check (public.is_card_language(get_language)),
  status text not null default 'pending'
    check (status in ('pending', 'accepted', 'declined', 'cancelled', 'completed')),
  -- each side marks the in-game trade as done; both done = completed
  from_done boolean not null default false,
  to_done boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (from_account <> to_account)
);
comment on table public.trade_offer is 'Trade offers between TCG Pocket accounts (written only through the trade functions)';

-- The same offer can't be open twice
create unique index trade_offer_one_open on public.trade_offer
  (from_account, to_account, give_card_id, give_language, get_card_id, get_language)
  where status in ('pending', 'accepted');
create index trade_offer_from_account on public.trade_offer (from_account);
create index trade_offer_to_account on public.trade_offer (to_account);

alter table public.trade_offer enable row level security;

create policy "Players can read offers on their accounts"
  on public.trade_offer for select to authenticated
  using (public.owns_tcg_account(from_account) or public.owns_tcg_account(to_account));

revoke all on public.trade_offer from anon, authenticated;
grant select on public.trade_offer to authenticated;


-- Name shown for an account: the player's username, else the Pocket name
create or replace function public.trade_account_name(account uuid) returns text
  language sql stable security definer set search_path = ''
  as $$
    select coalesce(u.username::text, a.tcg_id_username, 'Player')
    from public.player_tcg_account a
    left join public.user_account u on u.user_id = a.user_id
    where a.tcg_account_id = account
  $$;
revoke all on function public.trade_account_name(uuid) from public, anon, authenticated;


-- -----------------------------------------------------------------------------
-- find_trade_partners: cards other players have for trade that are on this
-- account's wishlist (same card, same language, tradable rarity). For each,
-- wanted_from_me lists this account's trade cards of the same rarity that the
-- other player has on their wishlist - the easiest offers to get accepted.
-- -----------------------------------------------------------------------------
create or replace function public.find_trade_partners(p_account uuid)
  returns table (
    partner_account uuid,
    partner_name text,
    get_card jsonb,
    get_language text,
    wanted_from_me jsonb
  )
  language plpgsql stable security definer set search_path = ''
  as $$
begin
  if not public.owns_tcg_account(p_account) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  return query
  with theirs as (
    select t.tcg_account_id as partner, t.card_id, t.language, c.rarity_id
    from public.cards_available_for_trade t
    join public.wishlist w on w.tcg_account_id = p_account and w.card_id = t.card_id and w.language = t.language
    join public.card c on c.card_id = t.card_id
    join public.player_tcg_account a on a.tcg_account_id = t.tcg_account_id
    where a.user_id <> (select auth.uid()) and public.rarity_is_tradable(c.rarity_id)
  )
  , rows as (
    select th.partner, th.card_id, th.language,
      coalesce((
        select jsonb_agg(jsonb_build_object('card', to_jsonb(mc), 'language', mt.language) order by mc.card_local_id)
        from public.cards_available_for_trade mt
        join public.card mc on mc.card_id = mt.card_id
        join public.wishlist pw on pw.tcg_account_id = th.partner and pw.card_id = mt.card_id and pw.language = mt.language
        where mt.tcg_account_id = p_account and mc.rarity_id = th.rarity_id
      ), '[]'::jsonb) as wanted
    from theirs th
  )
  select r.partner, public.trade_account_name(r.partner), to_jsonb(gc), r.language, r.wanted
  from rows r
  join public.card gc on gc.card_id = r.card_id
  order by jsonb_array_length(r.wanted) desc, 2, gc.card_local_id
  limit 300;
end $$;


-- -----------------------------------------------------------------------------
-- get_trade_offers: every offer on this account, from its point of view
-- (my_card = the card this account gives, their_card = the card it gets).
-- The partner's Pocket friend ID is only included once the offer is accepted.
-- -----------------------------------------------------------------------------
create or replace function public.get_trade_offers(p_account uuid)
  returns table (
    id bigint,
    direction text,
    status text,
    partner_account uuid,
    partner_name text,
    partner_friend_id text,
    my_card jsonb,
    my_language text,
    their_card jsonb,
    their_language text,
    i_marked_done boolean,
    partner_marked_done boolean,
    created_at timestamptz,
    updated_at timestamptz
  )
  language plpgsql stable security definer set search_path = ''
  as $$
begin
  if not public.owns_tcg_account(p_account) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  return query
  select
    o.id,
    case when o.from_account = p_account then 'outgoing' else 'incoming' end,
    o.status,
    case when o.from_account = p_account then o.to_account else o.from_account end,
    public.trade_account_name(case when o.from_account = p_account then o.to_account else o.from_account end),
    case when o.status in ('accepted', 'completed') then pa.tcg_id end,
    to_jsonb(case when o.from_account = p_account then gc else rc end),
    case when o.from_account = p_account then o.give_language else o.get_language end,
    to_jsonb(case when o.from_account = p_account then rc else gc end),
    case when o.from_account = p_account then o.get_language else o.give_language end,
    case when o.from_account = p_account then o.from_done else o.to_done end,
    case when o.from_account = p_account then o.to_done else o.from_done end,
    o.created_at,
    o.updated_at
  from public.trade_offer o
  join public.card gc on gc.card_id = o.give_card_id
  join public.card rc on rc.card_id = o.get_card_id
  join public.player_tcg_account pa
    on pa.tcg_account_id = case when o.from_account = p_account then o.to_account else o.from_account end
  where o.from_account = p_account or o.to_account = p_account
  order by o.updated_at desc
  limit 500;
end $$;


-- -----------------------------------------------------------------------------
-- create_trade_offer: p_from offers its p_give_card for p_to's p_get_card
-- -----------------------------------------------------------------------------
create or replace function public.create_trade_offer(
  p_from uuid, p_give_card uuid, p_give_language text,
  p_to uuid, p_get_card uuid, p_get_language text
) returns bigint
  language plpgsql security definer set search_path = ''
  as $$
declare
  partner_user uuid;
  give_rarity uuid;
  get_rarity uuid;
  rarity_ok boolean;
  new_id bigint;
begin
  if not public.owns_tcg_account(p_from) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  select user_id into partner_user from public.player_tcg_account where tcg_account_id = p_to;
  if partner_user is null then
    raise exception 'That player was not found' using errcode = 'P0002';
  end if;
  if partner_user = (select auth.uid()) then
    raise exception 'You cannot trade with your own account' using errcode = '22023';
  end if;

  if not exists (select 1 from public.cards_available_for_trade
                 where tcg_account_id = p_from and card_id = p_give_card and language = p_give_language) then
    raise exception 'That card is not on your trade list' using errcode = '22023';
  end if;
  if not exists (select 1 from public.cards_available_for_trade
                 where tcg_account_id = p_to and card_id = p_get_card and language = p_get_language) then
    raise exception 'The other player no longer has that card for trade' using errcode = '22023';
  end if;

  select c.rarity_id into give_rarity from public.card c where c.card_id = p_give_card;
  select c.rarity_id, public.rarity_is_tradable(c.rarity_id) into get_rarity, rarity_ok
    from public.card c where c.card_id = p_get_card;
  if give_rarity is distinct from get_rarity or not coalesce(rarity_ok, false) then
    raise exception 'Both cards must be the same rarity, and one the game lets you trade' using errcode = '22023';
  end if;

  if (select count(*) from public.trade_offer where from_account = p_from and status = 'pending') >= 50 then
    raise exception 'You have 50 offers waiting for an answer. Cancel some before sending more' using errcode = '54000';
  end if;

  begin
    insert into public.trade_offer (from_account, to_account, give_card_id, give_language, get_card_id, get_language)
    values (p_from, p_to, p_give_card, p_give_language, p_get_card, p_get_language)
    returning id into new_id;
  exception when unique_violation then
    raise exception 'You already sent this offer' using errcode = '23505';
  end;
  return new_id;
end $$;


-- -----------------------------------------------------------------------------
-- respond_trade_offer: the receiving player accepts or declines
-- -----------------------------------------------------------------------------
create or replace function public.respond_trade_offer(p_offer bigint, p_accept boolean) returns void
  language plpgsql security definer set search_path = ''
  as $$
declare
  o public.trade_offer;
begin
  select * into o from public.trade_offer where id = p_offer for update;
  if o.id is null or not public.owns_tcg_account(o.to_account) then
    raise exception 'Offer not found' using errcode = 'P0002';
  end if;
  if o.status <> 'pending' then
    raise exception 'This offer has already been answered' using errcode = '22023';
  end if;
  update public.trade_offer
    set status = case when p_accept then 'accepted' else 'declined' end, updated_at = now()
    where id = p_offer;
end $$;


-- -----------------------------------------------------------------------------
-- cancel_trade_offer: the sender withdraws a pending offer, or either player
-- backs out of an accepted one that neither has marked done
-- -----------------------------------------------------------------------------
create or replace function public.cancel_trade_offer(p_offer bigint) returns void
  language plpgsql security definer set search_path = ''
  as $$
declare
  o public.trade_offer;
begin
  select * into o from public.trade_offer where id = p_offer for update;
  if o.id is null or not (public.owns_tcg_account(o.from_account) or public.owns_tcg_account(o.to_account)) then
    raise exception 'Offer not found' using errcode = 'P0002';
  end if;
  if not (
    (o.status = 'pending' and public.owns_tcg_account(o.from_account))
    or (o.status = 'accepted' and not o.from_done and not o.to_done)
  ) then
    raise exception 'This offer can no longer be cancelled' using errcode = '22023';
  end if;
  update public.trade_offer set status = 'cancelled', updated_at = now() where id = p_offer;
end $$;


-- -----------------------------------------------------------------------------
-- mark_trade_done: a player confirms the in-game trade happened. Only their own
-- lists change: one copy of the card they gave comes off their trade list and
-- one copy of the card they got comes off their wishlist (if it was on it).
-- -----------------------------------------------------------------------------
create or replace function public.mark_trade_done(p_offer bigint) returns void
  language plpgsql security definer set search_path = ''
  as $$
declare
  o public.trade_offer;
  me uuid;
  gave_card uuid; gave_language text;
  got_card uuid; got_language text;
begin
  select * into o from public.trade_offer where id = p_offer for update;
  if o.id is null or not (public.owns_tcg_account(o.from_account) or public.owns_tcg_account(o.to_account)) then
    raise exception 'Offer not found' using errcode = 'P0002';
  end if;
  if o.status <> 'accepted' then
    raise exception 'Only accepted offers can be marked as done' using errcode = '22023';
  end if;

  if public.owns_tcg_account(o.from_account) and not o.from_done then
    me := o.from_account;
    gave_card := o.give_card_id; gave_language := o.give_language;
    got_card := o.get_card_id; got_language := o.get_language;
    update public.trade_offer set from_done = true, updated_at = now() where id = p_offer;
  elsif public.owns_tcg_account(o.to_account) and not o.to_done then
    me := o.to_account;
    gave_card := o.get_card_id; gave_language := o.get_language;
    got_card := o.give_card_id; got_language := o.give_language;
    update public.trade_offer set to_done = true, updated_at = now() where id = p_offer;
  else
    raise exception 'You already marked this trade as done' using errcode = '22023';
  end if;

  -- Delete the last copy first, otherwise a row just lowered to 1 would be deleted too
  delete from public.cards_available_for_trade
    where tcg_account_id = me and card_id = gave_card and language = gave_language and quantity = 1;
  update public.cards_available_for_trade set quantity = quantity - 1, updated_at = now()
    where tcg_account_id = me and card_id = gave_card and language = gave_language and quantity > 1;
  delete from public.wishlist
    where tcg_account_id = me and card_id = got_card and language = got_language and quantity = 1;
  update public.wishlist set quantity = quantity - 1, updated_at = now()
    where tcg_account_id = me and card_id = got_card and language = got_language and quantity > 1;

  update public.trade_offer set status = 'completed', updated_at = now()
    where id = p_offer and from_done and to_done;
end $$;


revoke all on function public.find_trade_partners(uuid) from public, anon;
revoke all on function public.get_trade_offers(uuid) from public, anon;
revoke all on function public.create_trade_offer(uuid, uuid, text, uuid, uuid, text) from public, anon;
revoke all on function public.respond_trade_offer(bigint, boolean) from public, anon;
revoke all on function public.cancel_trade_offer(bigint) from public, anon;
revoke all on function public.mark_trade_done(bigint) from public, anon;
grant execute on function public.find_trade_partners(uuid) to authenticated;
grant execute on function public.get_trade_offers(uuid) to authenticated;
grant execute on function public.create_trade_offer(uuid, uuid, text, uuid, uuid, text) to authenticated;
grant execute on function public.respond_trade_offer(bigint, boolean) to authenticated;
grant execute on function public.cancel_trade_offer(bigint) to authenticated;
grant execute on function public.mark_trade_done(bigint) to authenticated;
