-- =============================================================================
-- Exclusive trades
-- =============================================================================
-- A player picks one card from their trade list and the cards (same rarity) they
-- would take for it. That card then only trades through this listing: it no
-- longer shows up in Find trades, normal offers for it are refused, and other
-- players can only offer one of the listed cards, one pending offer each.
--
-- Removing the listing (or the card leaving the trade list) declines the
-- pending offers made through it and the card trades normally again.
-- =============================================================================


-- One listing per trade-list row; it goes away with the row
create table public.exclusive_trade (
  id bigint generated by default as identity primary key,
  trade_card_id bigint not null unique references public.cards_available_for_trade (id) on delete cascade,
  -- language the listed cards must be in
  want_language text not null check (public.is_card_language(want_language)),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
comment on table public.exclusive_trade is 'A trade-list card that only trades for the cards in exclusive_trade_want (written only through the exclusive trade functions)';

create table public.exclusive_trade_want (
  exclusive_trade_id bigint not null references public.exclusive_trade (id) on delete cascade,
  card_id uuid not null references public.card (card_id),
  primary key (exclusive_trade_id, card_id)
);

alter table public.trade_offer
  add column exclusive_trade_id bigint references public.exclusive_trade (id) on delete set null;
create index trade_offer_exclusive_trade on public.trade_offer (exclusive_trade_id);

-- Public like the lists themselves, so players can find them
alter table public.exclusive_trade enable row level security;
alter table public.exclusive_trade_want enable row level security;
create policy "Anyone can read exclusive trades"
  on public.exclusive_trade for select to anon, authenticated using (true);
create policy "Anyone can read what exclusive trades want"
  on public.exclusive_trade_want for select to anon, authenticated using (true);
revoke all on public.exclusive_trade, public.exclusive_trade_want from anon, authenticated;
grant select on public.exclusive_trade, public.exclusive_trade_want to anon, authenticated;


-- Is this account's card (in this language) held for an exclusive trade?
create or replace function public.card_is_exclusive(p_account uuid, p_card uuid, p_language text) returns boolean
  language sql stable set search_path = ''
  as $$
    select exists (
      select 1 from public.exclusive_trade e
      join public.cards_available_for_trade t on t.id = e.trade_card_id
      where t.tcg_account_id = p_account and t.card_id = p_card and t.language = p_language
    )
  $$;

-- Rarities that can be traded, so the app only offers those cards
create or replace function public.tradable_rarities() returns setof uuid
  language sql stable set search_path = ''
  as $$ select r.rarity_id from public.rarity r where public.rarity_is_tradable(r.rarity_id) $$;
grant execute on function public.tradable_rarities() to anon, authenticated;


-- Pending offers on a listing are declined when it goes away
create or replace function public.exclusive_trade_removed() returns trigger
  language plpgsql security definer set search_path = ''
  as $$
begin
  update public.trade_offer set status = 'declined', updated_at = now()
    where exclusive_trade_id = old.id and status = 'pending';
  return old;
end $$;
revoke all on function public.exclusive_trade_removed() from public, anon, authenticated;

create trigger exclusive_trade_removed before delete on public.exclusive_trade
  for each row execute function public.exclusive_trade_removed();


-- -----------------------------------------------------------------------------
-- save_exclusive_trade: create or change the listing for one trade-list card
-- -----------------------------------------------------------------------------
create or replace function public.save_exclusive_trade(p_trade_card bigint, p_want_language text, p_want_cards uuid[])
  returns bigint
  language plpgsql security definer set search_path = ''
  as $$
declare
  tc public.cards_available_for_trade;
  card_rarity uuid;
  wants uuid[];
  listing bigint;
begin
  select * into tc from public.cards_available_for_trade where id = p_trade_card;
  if tc.id is null or not public.owns_tcg_account(tc.tcg_account_id) then
    raise exception 'That card is not on your trade list' using errcode = '22023';
  end if;
  if not public.is_card_language(p_want_language) then
    raise exception 'Unknown language' using errcode = '22023';
  end if;

  select c.rarity_id into card_rarity from public.card c where c.card_id = tc.card_id;
  if not coalesce(public.rarity_is_tradable(card_rarity), false) then
    raise exception 'Cards of this rarity cannot be traded' using errcode = '22023';
  end if;

  select array_agg(distinct w) into wants from unnest(p_want_cards) w;
  if coalesce(array_length(wants, 1), 0) not between 1 and 50 then
    raise exception 'Pick between 1 and 50 cards' using errcode = '22023';
  end if;
  if exists (
    select 1 from unnest(wants) w
    left join public.card c on c.card_id = w
    where c.card_id is null or c.rarity_id is distinct from card_rarity
       or (w = tc.card_id and p_want_language = tc.language)
  ) then
    raise exception 'The cards you want must be the same rarity as your card' using errcode = '22023';
  end if;

  insert into public.exclusive_trade (trade_card_id, want_language) values (tc.id, p_want_language)
  on conflict (trade_card_id) do update set want_language = excluded.want_language, updated_at = now()
  returning id into listing;

  delete from public.exclusive_trade_want where exclusive_trade_id = listing;
  insert into public.exclusive_trade_want (exclusive_trade_id, card_id) select listing, w from unnest(wants) w;

  -- Offers this listing no longer takes: normal offers for the card, and
  -- exclusive ones for cards (or a language) no longer on the list
  update public.trade_offer o set status = 'declined', updated_at = now()
    where o.status = 'pending' and o.to_account = tc.tcg_account_id
      and o.get_card_id = tc.card_id and o.get_language = tc.language
      and (o.exclusive_trade_id is distinct from listing
           or o.give_language <> p_want_language
           or not (o.give_card_id = any (wants)));
  -- and the owner's own pending offers giving this card away
  update public.trade_offer o set status = 'cancelled', updated_at = now()
    where o.status = 'pending' and o.from_account = tc.tcg_account_id
      and o.give_card_id = tc.card_id and o.give_language = tc.language;

  return listing;
end $$;


-- -----------------------------------------------------------------------------
-- remove_exclusive_trade: the owner ends the listing (the card stays on the
-- trade list and trades normally again)
-- -----------------------------------------------------------------------------
create or replace function public.remove_exclusive_trade(p_exclusive bigint) returns void
  language plpgsql security definer set search_path = ''
  as $$
begin
  if not exists (
    select 1 from public.exclusive_trade e
    join public.cards_available_for_trade t on t.id = e.trade_card_id
    where e.id = p_exclusive and public.owns_tcg_account(t.tcg_account_id)
  ) then
    raise exception 'Exclusive trade not found' using errcode = 'P0002';
  end if;
  delete from public.exclusive_trade where id = p_exclusive;
end $$;


-- -----------------------------------------------------------------------------
-- find_exclusive_trades: other players' listings this account can answer,
-- i.e. it has one of the listed cards (in the wanted language) for trade.
-- Listings for cards on this account's wishlist come first.
-- -----------------------------------------------------------------------------
create or replace function public.find_exclusive_trades(p_account uuid)
  returns table (
    exclusive_trade_id bigint,
    partner_account uuid,
    partner_name text,
    card jsonb,
    language text,
    want_language text,
    on_my_wishlist boolean,
    i_can_give jsonb
  )
  language plpgsql stable security definer set search_path = ''
  as $$
begin
  if not public.owns_tcg_account(p_account) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  return query
  with listings as (
    select e.id, t.tcg_account_id as partner, t.card_id, t.language, e.want_language,
      (
        select jsonb_agg(to_jsonb(mc) order by mc.card_local_id)
        from public.exclusive_trade_want w
        join public.cards_available_for_trade mt
          on mt.tcg_account_id = p_account and mt.card_id = w.card_id and mt.language = e.want_language
        join public.card mc on mc.card_id = w.card_id
        where w.exclusive_trade_id = e.id
          and not public.card_is_exclusive(p_account, mt.card_id, mt.language)
      ) as can_give
    from public.exclusive_trade e
    join public.cards_available_for_trade t on t.id = e.trade_card_id
    join public.player_tcg_account a on a.tcg_account_id = t.tcg_account_id
    where a.user_id <> (select auth.uid())
  )
  select l.id, l.partner, public.trade_account_name(l.partner), to_jsonb(c), l.language, l.want_language,
    exists (select 1 from public.wishlist w where w.tcg_account_id = p_account and w.card_id = l.card_id and w.language = l.language),
    l.can_give
  from listings l
  join public.card c on c.card_id = l.card_id
  where l.can_give is not null
  order by 7 desc, 3, c.card_local_id
  limit 300;
end $$;


-- -----------------------------------------------------------------------------
-- send_exclusive_offer: offer one of the listed cards for a listing's card
-- -----------------------------------------------------------------------------
create or replace function public.send_exclusive_offer(p_from uuid, p_exclusive bigint, p_give_card uuid)
  returns bigint
  language plpgsql security definer set search_path = ''
  as $$
declare
  e public.exclusive_trade;
  tc public.cards_available_for_trade;
  partner_user uuid;
  new_id bigint;
begin
  if not public.owns_tcg_account(p_from) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  select * into e from public.exclusive_trade where id = p_exclusive;
  select * into tc from public.cards_available_for_trade where id = e.trade_card_id;
  if e.id is null or tc.id is null then
    raise exception 'This exclusive trade has ended' using errcode = 'P0002';
  end if;
  select user_id into partner_user from public.player_tcg_account where tcg_account_id = tc.tcg_account_id;
  if partner_user = (select auth.uid()) then
    raise exception 'You cannot trade with your own account' using errcode = '22023';
  end if;

  if not exists (select 1 from public.exclusive_trade_want where exclusive_trade_id = e.id and card_id = p_give_card) then
    raise exception 'That card is not one they asked for' using errcode = '22023';
  end if;
  if not exists (select 1 from public.cards_available_for_trade
                 where tcg_account_id = p_from and card_id = p_give_card and language = e.want_language) then
    raise exception 'That card is not on your trade list' using errcode = '22023';
  end if;
  if public.card_is_exclusive(p_from, p_give_card, e.want_language) then
    raise exception 'That card is in one of your exclusive trades' using errcode = '22023';
  end if;

  -- One pending offer per player per listing, so the owner isn't flooded
  if exists (select 1 from public.trade_offer
             where exclusive_trade_id = e.id and from_account = p_from and status = 'pending') then
    raise exception 'You already sent an offer for this exclusive trade' using errcode = '23505';
  end if;
  if (select count(*) from public.trade_offer where from_account = p_from and status = 'pending') >= 50 then
    raise exception 'You have 50 offers waiting for an answer. Cancel some before sending more' using errcode = '54000';
  end if;

  begin
    insert into public.trade_offer (from_account, to_account, give_card_id, give_language, get_card_id, get_language, exclusive_trade_id)
    values (p_from, tc.tcg_account_id, p_give_card, e.want_language, tc.card_id, tc.language, e.id)
    returning id into new_id;
  exception when unique_violation then
    raise exception 'You already sent this offer' using errcode = '23505';
  end;
  return new_id;
end $$;


-- -----------------------------------------------------------------------------
-- Normal trades leave cards held for an exclusive trade alone
-- -----------------------------------------------------------------------------
create or replace function public.find_trade_partners(p_account uuid)
  returns table (
    partner_account uuid,
    partner_name text,
    get_card jsonb,
    get_language text,
    wanted_from_me jsonb
  )
  language plpgsql stable security definer set search_path = ''
  as $$
begin
  if not public.owns_tcg_account(p_account) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  return query
  with theirs as (
    select t.tcg_account_id as partner, t.card_id, t.language, c.rarity_id
    from public.cards_available_for_trade t
    join public.wishlist w on w.tcg_account_id = p_account and w.card_id = t.card_id and w.language = t.language
    join public.card c on c.card_id = t.card_id
    join public.player_tcg_account a on a.tcg_account_id = t.tcg_account_id
    where a.user_id <> (select auth.uid()) and public.rarity_is_tradable(c.rarity_id)
      and not exists (select 1 from public.exclusive_trade e where e.trade_card_id = t.id)
  )
  , rows as (
    select th.partner, th.card_id, th.language,
      coalesce((
        select jsonb_agg(jsonb_build_object('card', to_jsonb(mc), 'language', mt.language) order by mc.card_local_id)
        from public.cards_available_for_trade mt
        join public.card mc on mc.card_id = mt.card_id
        join public.wishlist pw on pw.tcg_account_id = th.partner and pw.card_id = mt.card_id and pw.language = mt.language
        where mt.tcg_account_id = p_account and mc.rarity_id = th.rarity_id
          and not exists (select 1 from public.exclusive_trade e where e.trade_card_id = mt.id)
      ), '[]'::jsonb) as wanted
    from theirs th
  )
  select r.partner, public.trade_account_name(r.partner), to_jsonb(gc), r.language, r.wanted
  from rows r
  join public.card gc on gc.card_id = r.card_id
  order by jsonb_array_length(r.wanted) desc, 2, gc.card_local_id
  limit 300;
end $$;


create or replace function public.create_trade_offer(
  p_from uuid, p_give_card uuid, p_give_language text,
  p_to uuid, p_get_card uuid, p_get_language text
) returns bigint
  language plpgsql security definer set search_path = ''
  as $$
declare
  partner_user uuid;
  give_rarity uuid;
  get_rarity uuid;
  rarity_ok boolean;
  new_id bigint;
begin
  if not public.owns_tcg_account(p_from) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  select user_id into partner_user from public.player_tcg_account where tcg_account_id = p_to;
  if partner_user is null then
    raise exception 'That player was not found' using errcode = 'P0002';
  end if;
  if partner_user = (select auth.uid()) then
    raise exception 'You cannot trade with your own account' using errcode = '22023';
  end if;

  if not exists (select 1 from public.cards_available_for_trade
                 where tcg_account_id = p_from and card_id = p_give_card and language = p_give_language) then
    raise exception 'That card is not on your trade list' using errcode = '22023';
  end if;
  if not exists (select 1 from public.cards_available_for_trade
                 where tcg_account_id = p_to and card_id = p_get_card and language = p_get_language) then
    raise exception 'The other player no longer has that card for trade' using errcode = '22023';
  end if;
  if public.card_is_exclusive(p_from, p_give_card, p_give_language) then
    raise exception 'That card is in one of your exclusive trades' using errcode = '22023';
  end if;
  if public.card_is_exclusive(p_to, p_get_card, p_get_language) then
    raise exception 'That card only trades through its exclusive trade' using errcode = '22023';
  end if;

  select c.rarity_id into give_rarity from public.card c where c.card_id = p_give_card;
  select c.rarity_id, public.rarity_is_tradable(c.rarity_id) into get_rarity, rarity_ok
    from public.card c where c.card_id = p_get_card;
  if give_rarity is distinct from get_rarity or not coalesce(rarity_ok, false) then
    raise exception 'Both cards must be the same rarity, and one the game lets you trade' using errcode = '22023';
  end if;

  if (select count(*) from public.trade_offer where from_account = p_from and status = 'pending') >= 50 then
    raise exception 'You have 50 offers waiting for an answer. Cancel some before sending more' using errcode = '54000';
  end if;

  begin
    insert into public.trade_offer (from_account, to_account, give_card_id, give_language, get_card_id, get_language)
    values (p_from, p_to, p_give_card, p_give_language, p_get_card, p_get_language)
    returning id into new_id;
  exception when unique_violation then
    raise exception 'You already sent this offer' using errcode = '23505';
  end;
  return new_id;
end $$;


-- -----------------------------------------------------------------------------
-- respond_trade_offer: when accepting an exclusive offer uses up the owner's
-- last free copy, the other pending offers on that listing are declined
-- -----------------------------------------------------------------------------
create or replace function public.respond_trade_offer(p_offer bigint, p_accept boolean) returns void
  language plpgsql security definer set search_path = ''
  as $$
declare
  o public.trade_offer;
  copies integer;
begin
  select * into o from public.trade_offer where id = p_offer for update;
  if o.id is null or not public.owns_tcg_account(o.to_account) then
    raise exception 'Offer not found' using errcode = 'P0002';
  end if;
  if o.status <> 'pending' then
    raise exception 'This offer has already been answered' using errcode = '22023';
  end if;
  update public.trade_offer
    set status = case when p_accept then 'accepted' else 'declined' end, updated_at = now()
    where id = p_offer;

  if p_accept and o.exclusive_trade_id is not null then
    select t.quantity into copies from public.cards_available_for_trade t
      where t.tcg_account_id = o.to_account and t.card_id = o.get_card_id and t.language = o.get_language;
    if (select count(*) from public.trade_offer
        where exclusive_trade_id = o.exclusive_trade_id and status = 'accepted' and not to_done) >= coalesce(copies, 0) then
      update public.trade_offer set status = 'declined', updated_at = now()
        where exclusive_trade_id = o.exclusive_trade_id and status = 'pending';
    end if;
  end if;
end $$;


-- -----------------------------------------------------------------------------
-- get_trade_offers: now also says whether an offer came through an exclusive
-- trade (the return type changes, so the function is recreated)
-- -----------------------------------------------------------------------------
drop function public.get_trade_offers(uuid);
create function public.get_trade_offers(p_account uuid)
  returns table (
    id bigint,
    direction text,
    status text,
    partner_account uuid,
    partner_name text,
    partner_friend_id text,
    my_card jsonb,
    my_language text,
    their_card jsonb,
    their_language text,
    i_marked_done boolean,
    partner_marked_done boolean,
    exclusive_trade_id bigint,
    created_at timestamptz,
    updated_at timestamptz
  )
  language plpgsql stable security definer set search_path = ''
  as $$
begin
  if not public.owns_tcg_account(p_account) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;

  return query
  select
    o.id,
    case when o.from_account = p_account then 'outgoing' else 'incoming' end,
    o.status,
    case when o.from_account = p_account then o.to_account else o.from_account end,
    public.trade_account_name(case when o.from_account = p_account then o.to_account else o.from_account end),
    case when o.status in ('accepted', 'completed') then pa.tcg_id end,
    to_jsonb(case when o.from_account = p_account then gc else rc end),
    case when o.from_account = p_account then o.give_language else o.get_language end,
    to_jsonb(case when o.from_account = p_account then rc else gc end),
    case when o.from_account = p_account then o.get_language else o.give_language end,
    case when o.from_account = p_account then o.from_done else o.to_done end,
    case when o.from_account = p_account then o.to_done else o.from_done end,
    o.exclusive_trade_id,
    o.created_at,
    o.updated_at
  from public.trade_offer o
  join public.card gc on gc.card_id = o.give_card_id
  join public.card rc on rc.card_id = o.get_card_id
  join public.player_tcg_account pa
    on pa.tcg_account_id = case when o.from_account = p_account then o.to_account else o.from_account end
  where o.from_account = p_account or o.to_account = p_account
  order by o.updated_at desc
  limit 500;
end $$;


revoke all on function public.save_exclusive_trade(bigint, text, uuid[]) from public, anon;
revoke all on function public.remove_exclusive_trade(bigint) from public, anon;
revoke all on function public.find_exclusive_trades(uuid) from public, anon;
revoke all on function public.send_exclusive_offer(uuid, bigint, uuid) from public, anon;
revoke all on function public.get_trade_offers(uuid) from public, anon;
grant execute on function public.save_exclusive_trade(bigint, text, uuid[]) to authenticated;
grant execute on function public.remove_exclusive_trade(bigint) to authenticated;
grant execute on function public.find_exclusive_trades(uuid) to authenticated;
grant execute on function public.send_exclusive_offer(uuid, bigint, uuid) to authenticated;
grant execute on function public.get_trade_offers(uuid) to authenticated;
