-- =============================================================================
-- Cards on a player's TCG Pocket account: their wishlist and cards for trade
-- =============================================================================
-- Both tables existed but could not be used: wishlist.tcg_account_id was a
-- number (player_tcg_account uses a uuid), wishlist.language_id pointed at the
-- empty `language` table, and cards_available_for_trade had no account or
-- language column. Both were empty, so they are rebuilt here.
--
-- One row per account + card + language. Adding the same card again adds to
-- its quantity (see add_cards_to_tcg_account below).
-- =============================================================================

-- Refuse to run if either table has picked up rows since this was written
do $$
begin
  if exists (select 1 from public.wishlist) or exists (select 1 from public.cards_available_for_trade) then
    raise exception 'wishlist / cards_available_for_trade are not empty; migrate their rows instead of dropping';
  end if;
end $$;

drop table public.wishlist;
drop table public.cards_available_for_trade;

-- Language codes the app offers (usePokemonCardStore().languages)
create or replace function public.is_card_language(code text) returns boolean
  language sql immutable
  as $$ select code in ('en', 'es', 'fr', 'de', 'it', 'pt', 'jp', 'kr', 'ch') $$;

create table public.wishlist (
  id bigint generated by default as identity primary key,
  tcg_account_id uuid not null references public.player_tcg_account (tcg_account_id) on delete cascade,
  card_id uuid not null references public.card (card_id),
  -- language the player wants the card in
  language text not null check (public.is_card_language(language)),
  quantity integer not null check (quantity between 1 and 9999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tcg_account_id, card_id, language)
);
comment on table public.wishlist is 'Cards a TCG Pocket account wants';

create table public.cards_available_for_trade (
  id bigint generated by default as identity primary key,
  tcg_account_id uuid not null references public.player_tcg_account (tcg_account_id) on delete cascade,
  card_id uuid not null references public.card (card_id),
  -- language of the copies the player owns
  language text not null check (public.is_card_language(language)),
  quantity integer not null check (quantity between 1 and 9999),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (tcg_account_id, card_id, language)
);
comment on table public.cards_available_for_trade is 'Cards a TCG Pocket account offers for trade';


-- -----------------------------------------------------------------------------
-- Row Level Security: a user only sees and changes cards on their own accounts
-- -----------------------------------------------------------------------------
create or replace function public.owns_tcg_account(account uuid) returns boolean
  language sql stable
  as $$
    select exists (
      select 1 from public.player_tcg_account
      where tcg_account_id = account and user_id = (select auth.uid())
    )
  $$;

alter table public.wishlist enable row level security;
alter table public.cards_available_for_trade enable row level security;

create policy "Users can read their own wishlist"
  on public.wishlist for select to authenticated using (public.owns_tcg_account(tcg_account_id));
create policy "Users can add to their own wishlist"
  on public.wishlist for insert to authenticated with check (public.owns_tcg_account(tcg_account_id));
create policy "Users can update their own wishlist"
  on public.wishlist for update to authenticated
  using (public.owns_tcg_account(tcg_account_id)) with check (public.owns_tcg_account(tcg_account_id));
create policy "Users can remove from their own wishlist"
  on public.wishlist for delete to authenticated using (public.owns_tcg_account(tcg_account_id));

create policy "Users can read their own trade cards"
  on public.cards_available_for_trade for select to authenticated using (public.owns_tcg_account(tcg_account_id));
create policy "Users can add their own trade cards"
  on public.cards_available_for_trade for insert to authenticated with check (public.owns_tcg_account(tcg_account_id));
create policy "Users can update their own trade cards"
  on public.cards_available_for_trade for update to authenticated
  using (public.owns_tcg_account(tcg_account_id)) with check (public.owns_tcg_account(tcg_account_id));
create policy "Users can remove their own trade cards"
  on public.cards_available_for_trade for delete to authenticated using (public.owns_tcg_account(tcg_account_id));

-- Signed-out visitors have no business with these tables
revoke all on public.wishlist, public.cards_available_for_trade from anon;
grant select, insert, update, delete on public.wishlist, public.cards_available_for_trade to authenticated;


-- -----------------------------------------------------------------------------
-- player_tcg_account: the live policy "get" lets any signed-in user read and
-- change every account. Replace it with owner-only policies (as drafted in
-- supabase/rls-policies.sql).
-- -----------------------------------------------------------------------------
drop policy if exists "get" on public.player_tcg_account;

create policy "Users can read their own TCG accounts"
  on public.player_tcg_account for select to authenticated using (user_id = (select auth.uid()));
create policy "Users can add their own TCG accounts"
  on public.player_tcg_account for insert to authenticated with check (user_id = (select auth.uid()));
create policy "Users can update their own TCG accounts"
  on public.player_tcg_account for update to authenticated
  using (user_id = (select auth.uid())) with check (user_id = (select auth.uid()));
create policy "Users can delete their own TCG accounts"
  on public.player_tcg_account for delete to authenticated using (user_id = (select auth.uid()));


-- -----------------------------------------------------------------------------
-- add_cards_to_tcg_account: save a batch of selected cards in one go.
--   p_category: 'wishlist' or 'trade' (CARD_CATEGORY in src/constants.ts)
--   p_cards:    [{ "card_id": uuid, "language": "en", "quantity": 2 }, ...]
-- Cards already on the list get the new quantity added to what is there.
-- Security invoker, so the RLS policies above decide what the caller may touch;
-- the ownership check up front just gives a clear error instead of a policy one.
-- -----------------------------------------------------------------------------
create or replace function public.add_cards_to_tcg_account(p_tcg_account_id uuid, p_category text, p_cards jsonb)
  returns integer
  language plpgsql
  security invoker
  set search_path = ''
  as $$
declare
  saved integer;
begin
  if not public.owns_tcg_account(p_tcg_account_id) then
    raise exception 'TCG account not found' using errcode = '42501';
  end if;
  if jsonb_typeof(p_cards) <> 'array' or jsonb_array_length(p_cards) = 0 then
    raise exception 'No cards to add' using errcode = '22023';
  end if;

  if p_category = 'wishlist' then
    insert into public.wishlist as w (tcg_account_id, card_id, language, quantity)
    select p_tcg_account_id, c.card_id, c.language, sum(c.quantity)
    from jsonb_to_recordset(p_cards) as c(card_id uuid, language text, quantity integer)
    group by c.card_id, c.language
    on conflict (tcg_account_id, card_id, language)
      do update set quantity = w.quantity + excluded.quantity, updated_at = now();
  elsif p_category = 'trade' then
    insert into public.cards_available_for_trade as t (tcg_account_id, card_id, language, quantity)
    select p_tcg_account_id, c.card_id, c.language, sum(c.quantity)
    from jsonb_to_recordset(p_cards) as c(card_id uuid, language text, quantity integer)
    group by c.card_id, c.language
    on conflict (tcg_account_id, card_id, language)
      do update set quantity = t.quantity + excluded.quantity, updated_at = now();
  else
    raise exception 'Unknown card category %', p_category using errcode = '22023';
  end if;

  get diagnostics saved = row_count;
  return saved;
end $$;

revoke all on function public.add_cards_to_tcg_account(uuid, text, jsonb) from public, anon;
grant execute on function public.add_cards_to_tcg_account(uuid, text, jsonb) to authenticated;
